### ISSUE TITLE
Font renders poorly in javascript

### ISSUE THREAD

**Issue by dhowe** [dhowe/PerceptualReader#7]
JS on the left, Java on the right:

![screen shot 2017-05-25 at 1 00 09 pm](https://cloud.githubusercontent.com/assets/737638/26436598/3f763b9a-414a-11e7-8b9b-020e43548029.png)

**Comment by dhowe** [comment]
A solution may be drawing to a higher resolution canvas, as per [this post](https://stackoverflow.com/questions/15661339/how-do-i-fix-blurry-text-in-my-html5-canvas)

**Comment by cqx931** [comment]
Currently, once the border is hidden, the font renders poorly again.
https://github.com/dhowe/PerceptualReader/blob/master/code.js#L132
Works fine after removing the line above, is this intended?

**Comment by dhowe** [comment]
Fixed
